##Spring Configuration
server:
  port: 8081
spring:
  application:
    name: bills-payment
  devtools:
    add-properties: false
management:
  endpoint:
    health:
      show-details: always
  profiles:
    include:
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG